#! python


def build(ctx):

    ctx(
        features="run_r_script",
        source="transform_data.r",
        target=[
            ctx.path_to(ctx, "OUT_DATA", "Grossarl.csv"),
            ctx.path_to(ctx, "OUT_DATA", "GermanM1.csv"),
        ],
        deps=[
            ctx.path_to(ctx, "IN_DATA", "Grossarl.rda"),
            ctx.path_to(ctx, "IN_DATA", "GermanM1.rda")
        ],
        name="transform_data",
    )

    ctx(
        features="run_py_script",
        source="clean_data.py",
        target=ctx.path_to(ctx, "OUT_DATA", "col_historic_homicide.csv"),
        deps=ctx.path_to(ctx, "IN_DATA", "homicide_rate_by_country.csv"),
        name="clean_data",
    )
