#! python


def build(ctx):

    for model in "baseline", "max_moves_2":

        ctx(
            features="run_py_script",
            source="plot_locations.py",
            deps=[
                ctx.path_to(ctx, "OUT_ANALYSIS", f"schelling_{model}.pickle"),
                ctx.path_to(ctx, "IN_MODEL_SPECS", f"{model}.json"),
            ],
            target=ctx.path_to(ctx, "OUT_FIGURES", f"schelling_{model}.png"),
            append=model,
            name=f"plot_locations_{model}",
        )

    ctx(
        features="run_py_script",
        source="plots.py",
        deps=[
            ctx.path_to(ctx, "OUT_ANALYSIS", "colombia_hom_breaks.pickle"),
            ctx.path_to(ctx, "OUT_ANALYSIS", "timing_info.pickle"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "colombia_hom.png"),
            ctx.path_to(ctx, "OUT_FIGURES", "colombia_hom_bp.png"),
            ctx.path_to(ctx, "OUT_FIGURES", "runtimes_plot.png"),
        ],
        name="plots",
    )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
