#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="empirical_analysis.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "col_historic_homicide.csv"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "breakpoints.py"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_ANALYSIS", "colombia_hom_breaks.pickle"),
        ],

        name="empirical_analysis",
    )

    ctx(
        features="run_py_script",
        source="timing.py",
        deps=ctx.path_to(ctx, "IN_MODEL_CODE", "breakpoints.py"),
        target=ctx.path_to(ctx, "OUT_ANALYSIS", "timing_info.pickle"),

        name="timing",
    )
